### ISSUE TITLE
How to run this with a Python 2 instead of Python3

### ISSUE THREAD

**Issue by geekyfox90** [timhughes/git-credential-libsecret#1]
It would be great to have a Python 2 version of this amazing script instead of Python3

**Comment by timhughes** [comment]
I wrote this because at the time the gnome keyring git integration didn't work with libsecret. I no longer use it and this repo is here in case someone else finds the code useful for something. I would recommend using the standard helper `/usr/libexec/git-core/git-credential-gnome-keyring` or one of the others available at `/usr/libexec/git-core/git-credential-*` or somewhere similar depending on your distro.
